name: 'QMS Manual Checks'
description: 'Checks for manual tags in the files'
inputs:
  feature_files_dir:
    description: 'Path to the files'
    required: true
    default: '.'
  tag:
    description: 'Tag to check for'
    required: true

outputs:
  manual_tag:
    description: 'boolean if the tag is found'
    value: ${{ steps.manual-checks.outputs.manual_tag }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true

    - name: debug
      run: |
        echo "feature_files_dir: ${{ inputs.feature_files_dir }}"
        echo "tag: ${{ inputs.tag }}"
        SCRIPTS_DIR='/home/runner/work/_actions/nn-dma/manual-checks/main/scripts'
        # echo $(bash $SCRIPTS_DIR/qms-scripts last-sha)
        git tag -l "release#*" | sort -V | tail -n 1
        echo "***"
        git tag -l "release#*" | sort -V

      shell: bash

    - name: Latest SHA
      id: latest-sha
      run: |
        SCRIPTS_DIR='/home/runner/work/_actions/nn-dma/manual-checks/main/scripts'
        # echo "latest_sha=$(bash $SCRIPTS_DIR/qms-scripts last-sha)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check for manual tags
      id: manual-checks
      run: |
        echo "Checking for manual tags"
        # git diff --name-only ${{ steps.latest-sha.outputs.latest_sha }} HEAD
        # SCRIPTS_DIR='/home/runner/work/_actions/nn-dma/manual-checks/main/scripts'
        # EXITS=$(bash $SCRIPTS_DIR/qms-scripts check -p ${{ inputs.feature_files_dir }} -t ${{ inputs.tag }} -m)
        # if [ -z "$EXITS" ]; then
        #   echo "manual_tag=true" >> $GITHUB_OUTPUT
        # else
        #  echo "manual_tag=false" >> $GITHUB_OUTPUT
        # fi
      shell: bash
