name: 'QMS Manual Checks'
description: 'Checks for manual tags in the files'
inputs:
  feature_files_dir:
    description: 'Path to the files'
    required: true
    default: '.'
  tag:
    description: 'Tag to check for'
    required: true

outputs:
  manual_pv:
    description: 'boolean if the tag is found'
    value: ${{ steps.manual-checks.outputs.manual_pv }}
  manual_iv:
    description: 'boolean if the tag is found'
    value: ${{ steps.manual-checks.outputs.manual_iv }}

runs:
  using: 'composite'
  steps:
    - name: Check for manual tags
      id: manual-checks
      env:
        TAG: ${{ inputs.tag }}
      run: |
        echo "Checking for manual tags"
        SCRIPTS_DIR='/home/runner/work/_actions/nn-dma/manual-checks/main/scripts'
        EXITS=$(bash $SCRIPTS_DIR/qms-scripts check -p ${{ inputs.feature_files_dir }} -t $TAG -m)
        OUPUT_NAMESPACE='manual_${TAG}'
        echo "$OUPUT_NAMESPACE"
        if [ -z "$EXITS" ]; then
          echo "${OUPUT_NAMESPACE}=false" >> $GITHUB_OUTPUT
        else
          echo "${OUPUT_NAMESPACE}=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
