name: 'QMS Manual Checks'
description: 'Checks for manual tags in the files'
inputs:
  feature_files_dir:
    description: 'Path to the files'
    required: true
    default: '.'
  tag:
    description: 'Tag to check for'
    required: true
  repo_tag:
    description: 'Giving the option to specify another version of the manual-checks repo or a GitHub SHA.'
    required: false
    default: 'v1.0.5'

outputs:
  manual_pv:
    description: 'boolean if the tag is found'
    value: ${{ steps.manual-checks.outputs.manual_PV }}
  manual_iv:
    description: 'boolean if the tag is found'
    value: ${{ steps.manual-checks.outputs.manual_IV }}

runs:
  using: 'composite'
  steps:
    - name: Check for manual tags
      id: manual-checks
      run: |
        echo "Checking for manual tags"
        ls /home/runner/work/_actions/NovoNordisk-OpenSource/manual-checks/
        SCRIPTS_DIR='/home/runner/work/_actions/NovoNordisk-OpenSource/manual-checks/${{ inputs.repo_tag  }}/scripts'
        EXITS=$(bash $SCRIPTS_DIR/qms-scripts check -p ${{ inputs.feature_files_dir }} -t ${{ inputs.tag }} -m)
        OUTPUT_NAMESPACE='manual_${{ inputs.tag }}'
        echo "$OUTPUT_NAMESPACE"
        if [ -z "$EXITS" ]; then
          echo "${OUTPUT_NAMESPACE}=false" >> $GITHUB_OUTPUT
        else
          echo "${OUTPUT_NAMESPACE}=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
