name: 'QMS Manual Checks'
description: 'Checks for manual tags in the files'
inputs:
  feature_files_dir:
    description: 'Path to the files'
    required: true
    default: '.'
  tag:
    description: 'Tag to check for'
    required: true

outputs:
  manual_tag:
    description: 'boolean if the tag is found'
    value: ${{ steps.manual-checks-${{ inputs.tag }}.outputs.manual_tag }}

env:
  SCRIPTS_DIR: '/home/runner/work/_actions/nn-dma/qms-manual-checks/main/scripts'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check for manual tags
      id: manual-checks-${{ inputs.tag }}
      run: |
        SCRIPTS_DIR='/home/runner/work/_actions/nn-dma/manual-checks/main/scripts'
        EXITS=$(bash $SCRIPTS_DIR/qms-scripts check -p ${{ inputs.feature_files_dir }} -t ${{ inputs.tag }} -m)
        if [ -z "$EXITS" ]; then
          echo "MANUAL_${{ inputs.tag }}=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
